### PR TITLE
Added people and projects

### PR DESCRIPTION
**Pull request by mestaritonttu**
People:
Andrius Štikonas, Jacky Alcine, skypjack, Stjepan Glavina

Projects:
Duplicati, Lollipop Cloud, Olive, Open Broadcaster Software, openage, phpMyAdmin, Prismo, ReactOS, Zig

I hope Jacky can be accepted now that Koype has a website:
https://koype.net/
Latest news: https://v2.jacky.wtf/post/2019-may-koype

### CODE REVIEW

**Comment by uraimo** [comment]
Hi mestaritonttu, thanks again!!
Are we 100% sure about the phpMyAdmin link? I can't seem to find it on phpmyadmin.net.
I'll put ReactOS under "Operating Systems" later.

About Jackie hmm, I don't know the guy, but it's still pretty vague/unclear what the project actually is, if it actually is something tangible, what works and what not and the real entity of the updates in the last few months, **imho**, so much so that last time I considered writing additional but very basic rules for new (i.e. not long established, with 0 following of any kind) projects/developers.
And a few projects currently in list would not likely fit the bill (no updates, the projects were never updated, they are opensource in the sense that the source is there but no one will ever even think of using it considering its current state or simply are still stubs for something that never came to be).

I didn't plan to be unnecessarily strict providing too many "rules" and I'm trying to forego the "awesomeness" requirement typical of the other awesome-lists since it's a bit subjective.
But I'm worried that accepting everyone indiscriminately the list will soon start to be polluted with projects by people trying to see if they can make a quick buck with some random code and a well crafted Patreon account.

**Comment by mestaritonttu** [comment]
From the docs of Koype:

> Koype is Web software that provides its user with implementations of
> 
>     IndieAuth, a personalized take on authentication,
>     MicroPub, a means of publishing content on one’s Website
>     Webmentions, a means of receiving interactions from other sites.

Why would it not be something tangible? Jacky has been dogfooding it for quite a while now at https://v2.jacky.wtf/
It's as important and relevant as any of the federated social web projects. I think this is getting to the point that you need to make better arguments against including him. I'm certainly not convinced of your arguments so far and have put in a lot of work laying out in plain terms why he is relevant.

**Comment by uraimo** [comment]
> Why would it not be something tangible? Jacky has been dogfooding it for quite a while now
This is the first time I see it and it seems half-broken, but could be acceptable for these kind of federated platforms.
Please keep in mind that I've really never heard of the guy and not even of IndieWeb (and what is the relationship between the two). My opinion is just the result of what I saw.

>  I'm certainly not convinced of your arguments so far 
No problem, let me describe my reasoning behind the first rejection and this one to see if I can derive some general rules of thumb for future projects submissions.

The last time I've looked into this, starting from that list of repos but also searching via google for info on this project since I couldn't understand what it actually did (I've tried to be thorough), what I found in addition to the main repo (that I didn't test, but a lot of things felt out of place and half done) were a lot of empty repos (or worse, weird repos with empty files...) and repos that were just clones of other projects without additional commits (ok, there are a lot of reason to fork stuff à la github). Not much else that I could find.
The textual stuff I could find online (current or obsolete, I don't know) was full of broken links and *very* generic and enthusiastic vague descriptions with no related implementation.
When I looked at the Patreon account, I've found a lot of vague plans and especially a post on a 0.0.5 release followed by stuff about a 1.0.0 release two weeks later and other stuff on plans. All this *felt to me* as something extremely sketchy, or at least as a project very badly presented.

The fact is, this is a list for people writing software and while I don't really care how popular a project is (popularity doesn't matter, the number of stars or followers on github don't matter) I want to be 101% certain of the effort that has put in in the project and that the project is not something that could be replicated in a few days, that has been put up just to see if asking for money via Patreon works or something like that.
In this case, *with my completely subjective review based on what I saw* I concluded that this project was, trying to be optimistic, not in a state in which I felt comfortable to seeing it included here. Maybe in a few months.

Fast forward to now,  a new short planning blog post and a good number of small (hard to day what they've improved) commits have been added to the main repo. Sorry this still gives me the same impression of last time.
Serious question, have you tried it and does it work? Yes/No.

So, if I had to come up with rules that informed the decision above (and more) and that could be applied to future submissions (wording can be improved):
1 - Projects that require negligible amount of effort to be replicated or individual with minimal contributions to open source projects will not be accepted.
2 - Asking for contributions makes sense only when there is a verifiable history of released software and open source contributions, not the other way around. Wait and release software for a few months before considering asking for donations, projects/individual that do these two things backward will not be accepted. 
3 - Your project should be usable by your users and contributors from the point of view of clearly stated scope, carefully crafted and tested install instruction and usage description. Projects that are half-done, that don't clearly state what the project does or don't care about people actually using it will not be accepted. Show that you care, don't just dump code somewhere and call it open source.
4- This list sole aim is to help software developers and their projects with their funding campaigns. People developing actual software, not planning about developing software or selling some grand vision for software that will never materialize. As said above, if you are asking for monetary contributions make a case for it through the software you already shipped in a usable form.

In my opinion, with the information I have right now, I have doubts regarding [1], [3], and [4].
Could this change in a few months? I have even more doubts about this than last time.

**Comment by mestaritonttu** [comment]
> Serious question, have you tried it and does it work? Yes/No.

I tried it just now and here is a screenshot of the setup screen on my computer: https://imgur.com/a/tAaQEUq
I used the docker-compose setup, removing the Selenium test containers from the .yml.

**Comment by uraimo** [comment]
And after the setup screen (I don't need screenshots, I'm just asking for an honest/substantiated  opinion)? 

Also, since you say you've put in a lot of work for this *specific* entry,  does it really have implementations for the listed IndieAuth, MicroPub and Webmentions or it is just a web interface cobbled together that use external projects?
It seems to me like stuff that already have well known implementations, and I don't see specific subprojects implementing any of those *as I would expect*.

Let me be clear, I don't want to include in this list stuff that I can't even understand if it could have any general value for other people (and motivate any request for money).
I'm not even sure why we are losing so much time on this since it doesn't look comparable to the other stuff we have on the list. Am I missing something here?

**Comment by uraimo** [comment]
On second thoughts, we have already spent too much time on this, let's just end it so that we can use our time for something more productive.
The project will not be added for [1],[3] and [4], I don't care enough to investigate further.

**Comment by uraimo** [comment]
Found by chance his github account in the 3rd page of the search results... that would have been a way better way to present what he does since there he has contributions going back to 2010, and also had what I was searching for.
Added with another commit.

**Comment by mestaritonttu** [comment]
> Found by chance his github account in the 3rd page of the search results... that would have been a way better way to present what he does since there he has contributions going back to 2010, and also had what I was searching for.

Can you explain how it is better and what was it that you were searching for? I would rather have though the present day is more important than 2010. If we look at the bulk of his activity for the past several months, it is simply his Koype repo mirrored to GitHub.

**Pull request merged**
